# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Set environment variables for the PostgreSQL database
ENV POSTGRES_DB=passgen
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=Helpless-Phrase-Unrushed-Radar0-Buzz-Curling-Haggler

# Expose the PostgreSQL port
EXPOSE 5432

